# lib/mikrotik-dns.nix — RouterOS side of the anycast DNS fleet
#
# Rendered from hosts/dns/nodes.nix, so the router can never drift from the
# node list. Idempotent: everything is tagged and replaced on each import.
# One-time router setup (not managed here): /routing/bgp/instance, and
# pointing DHCP clients at the anycast address.
{ lib, dns }:

let
  inherit (dns) site nodes;
  tag = ''comment="nix:dns-anycast"'';

  connection = name: node:
    "/routing/bgp/connection add name=${name} ${tag} instance=${site.mikrotik.bgpInstance}"
    + " local.role=ebgp remote.address=${node.address}/32 remote.as=${toString site.bgp.nodeAS}"
    + " hold-time=9s keepalive-time=3s input.filter=dns-anycast-in connect=yes listen=yes\n";
in
''
  # Generated by `nix build .#mikrotik-dns` — do not edit by hand.
  # Re-importing resets the BGP sessions: expect a few seconds of failover.

  /routing/bgp/connection remove [find ${tag}]
  /routing/filter/rule remove [find ${tag}]
  /ip firewall raw remove [find ${tag}]

  /routing/filter/rule add chain=dns-anycast-in ${tag} rule="if (dst == ${site.anycastAddress}/32) { accept }"
  /routing/filter/rule add chain=dns-anycast-in ${tag} rule="reject"

  ${lib.concatStrings (lib.mapAttrsToList connection nodes)}
  # Nodes share the clients' subnet, so replies bypass the router:
  # don't let conntrack mark that half-seen traffic invalid, and don't
  # ICMP-redirect clients straight to one node (that would pin them to it).
  /ip firewall raw add chain=prerouting dst-address=${site.anycastAddress} action=notrack ${tag}
  /ip settings set send-redirects=no
''
