# lib/mikrotik-dns.nix — RouterOS side of the anycast DNS fleet
#
# Rendered from hosts/dns/nodes.nix, so the router can never drift from the
# fleet. Idempotent: everything is tagged and replaced on each import.
#
# Nodes take their address from DHCP, so this is a *dynamic* peer listener
# for the whole subnet rather than one connection per node — importing this
# once covers every node you will ever add. `connect=no` is required: the
# router cannot dial a subnet, so the nodes always initiate.
#
# Trade-off: any host on site.lan.subnet that speaks BGP with AS
# site.bgp.nodeAS can peer. The dns-anycast-in filter limits *what* may be
# announced to the anycast /32, but not *who* may announce it. Add a shared
# tcp-md5-key here and in services.bird if that subnet ever carries
# untrusted devices.
#
# One-time router setup (not managed here): /routing/bgp/instance, and
# pointing DHCP clients at the anycast address.
{ dns }:

let
  inherit (dns) site;
  tag = ''comment="nix:dns-anycast"'';
in
''
  # Generated by `nix build .#mikrotik-dns` — do not edit by hand.
  # Re-importing resets the BGP sessions: expect a few seconds of failover.

  /routing/bgp/connection remove [find ${tag}]
  /routing/filter/rule remove [find ${tag}]
  /ip firewall raw remove [find ${tag}]

  /routing/filter/rule add chain=dns-anycast-in ${tag} rule="if (dst == ${site.anycastAddress}/32) { accept }"
  /routing/filter/rule add chain=dns-anycast-in ${tag} rule="reject"

  /routing/bgp/connection add name=dns-anycast ${tag} instance=${site.mikrotik.bgpInstance} \
      local.role=ebgp remote.address=${site.lan.subnet} remote.as=${toString site.bgp.nodeAS} \
      hold-time=9s keepalive-time=3s input.filter=dns-anycast-in connect=no listen=yes

  # Nodes share the clients' subnet, so replies bypass the router:
  # don't let conntrack mark that half-seen traffic invalid, and don't
  # ICMP-redirect clients straight to one node (that would pin them to it).
  /ip firewall raw add chain=prerouting dst-address=${site.anycastAddress} action=notrack ${tag}
  /ip settings set send-redirects=no
''
